### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by CVUsers** [insigh1/GA_Data_Science_Capstone#2]
Hello, I am in the direction of AI algorithm. I sincerely ask you for gesture your training data set, and I can exchange it with you. I have 40Gb gesture classification data and 5000 gesture data of target detection. I do not do business, but I study for the purpose. I hope you can share the data with me. Thank you 2665312447@qq.com Or through Baidu disk or through Google and other ways.

**Comment by robmarkcole** [comment]
@insigh1 am also interested in the dataset, perhaps you could make it available on Kaggle or similar? Best regards

**Comment by CVUsers** [comment]
I am Chinese, I have put all the data on my side, I can share it with you through Baidu SkyDrive, this is my WeChat official account, you can find me from it. https://mp.weixin.qq.com/s/m-bn-Q0dhfav-YsI5b-oLg

**Comment by insigh1** [comment]
Hello @robmarkcole @CVUsers.  I have publicly shared my dataset here: https://public.roboflow.com/object-detection/american-sign-language-letters/1

I believe my original dataset was 700 images, so the additional ones may have been augmentations performed by roboflow.  I hope that helps!

I may upload to Kaggle in the future.
