### ISSUE TITLE
Is there phcharm version?

### ISSUE THREAD

**Issue by yister0321** [insigh1/GA_Data_Science_Capstone#3]
Excuse me, Do you have a pycharm version of the project that can be run? I am a amateur of computer vision algorithm, and I need a executable project. If you can give me, I will be very grateful to you. My e-mail : yztramboo@163.com

**Comment by insigh1** [comment]
I haven't worked on pycharm IDE.  I think a good reference for learning how to runa  project is here: https://blog.roboflow.com/how-to-train-yolov5-on-a-custom-dataset/

This one is on a google colab notebook

**Comment by SUN-LIGHT-X** [comment]
Excuse me, I'm aamateur of computer vision algorithm. There are some difficulties in my study. Can you share it best.pt Do you have any documents?
Thank you. My email address is hujinhao000715@163.com
Thank you again for your help.

**Comment by yister0321** [comment]
I'm sorry. There are no datasets, so I can not help you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SUN-LIGHT-X"<notifications@github.com&gt;; 
发送时间: 2020年12月26日(星期六) 中午12:21
收件人: "insigh1/Interactive_ABCs_with_American_Sign_Language_using_Yolov5"<Interactive_ABCs_with_American_Sign_Language_using_Yolov5@noreply.github.com&gt;; 
抄送: "DesertStorm"<464151490@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [insigh1/Interactive_ABCs_with_American_Sign_Language_using_Yolov5] Is there phcharm version? (#3)





 
Excuse me, I'm aamateur of computer vision algorithm. There are some difficulties in my study. Can you share it best.pt Do you have any documents?
 Thank you. My email address is hujinhao000715@163.com
 Thank you again for your help.
