### ISSUE TITLE
Data Augmentation .

### ISSUE THREAD

**Issue by tutu96177** [insigh1/GA_Data_Science_Capstone#4]
Thanks to the author for an excellent job. I have some questions for you, 
1. How do I get 720 images and labels?
2. The 720 images and labels grew into data augmentation to 18,000 images and labels, and what scripts will need to be run?

**Comment by insigh1** [comment]
I have publicly shared my dataset here: https://public.roboflow.com/object-detection/american-sign-language-letters/1

I used a library called albumentations for augmentations.  I would refer to their documentation: https://albumentations.ai/docs/

**Comment by DimaMirana** [comment]
Hello, can you share the augmented 18k image dataset? Also If I want to cite your dataset what's the bibtex format of the citation?
